### ISSUE TITLE
Connect to polkadot node

### ISSUE THREAD

**Issue by mpetrunic** [NodeFactoryIo/vedran-daemon#4]
- should get node config, sort alphabetically and hash
- should get metrics required in https://github.com/NodeFactoryIo/vedran/issues/4

**Comment by mpetrun5** [comment]
@mpetrunic 
Do you know maybe what node config should consist of?
Currently, I hashed available rpc methods. Anything else?

**Comment by mpetrunic** [comment]
I've asked bruno. My best guess is that you would need to add stuff from chain() rpc and maybe metadata()

**Comment by mpetrunic** [comment]
Npt sure what metadata will return though
